using Microsoft.EntityFrameworkCore;
using WebApi.Data.Context;
using WebApi.Data.Models;
using WebApi.Repository.IRepo;

namespace WebApi.Repository.Repositories
{
    public class EmployeeRepository : IGenericRepository<Employee>
    {
        private readonly DexefdbSampleContext _dbContext;

        public EmployeeRepository(DexefdbSampleContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IEnumerable<Employee>?> GetAllAsync()
        {
            return await _dbContext.Employees.ToListAsync();
        }


        public async Task<Employee?> GetByIdAsync(int id)
        {
            var employee = await _dbContext.Set<Employee>().FindAsync(id);
            return employee;
        }

        public async Task<Employee> AddAsync(Employee entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException(nameof(entity));
            }

            else
            {
                try
                {
                    // reset id (if user enter id by mistake (sql server is generated by sql server))
                    entity.Id = 0;
                    var employee = _dbContext.Set<Employee>().Add(entity);
                    await _dbContext.SaveChangesAsync();
                    return employee.Entity;
                }
                catch (Exception ex)
                {
                    throw;
                }
            }

        }


        public async Task<bool> DeleteAsync(int id)
        {
            var employee = await GetByIdAsync(id);
            if (employee == null)
            {
                return false;
            }
            else
            {
                try
                {
                    _dbContext.Set<Employee>().Remove(employee);
                    await _dbContext.SaveChangesAsync();
                    return true;
                }
                catch (Exception ex)
                {
                    throw;
                }

            }
        }

        public async Task<bool> UpdateAsync(Employee entity)
        {

            var employee = await GetByIdAsync(entity.Id);
            if (employee == null)
            {
                return false;
            }
            else
            {
                try

                {
                    // reset id (if user enter id by mistake (sql server is generated by sql server))
                    entity.Id = 0;
                    _dbContext.Employees.Update(entity);
                    await _dbContext.SaveChangesAsync();
                    return true;
                }
                catch (Exception ex)
                {
                    throw;
                }

            }
        }


    }
}
